name: CountryWeather CI Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    inputs:
      env:
        description: 'Domain to test (countries, weather, or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - countries
          - weather

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.14.5
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.5'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          TARGET_ENV: ${{ github.event.inputs.env || 'all' }}
        run: |
          mkdir -p allure-results
          # Replace 'tests/' with the path to your test folder if different
          pytest tests/ --env=$TARGET_ENV --alluredir=allure-results

      - name: Generate Allure Report
        if: always()
        run: |
          sudo apt-get update && sudo apt-get install -y default-jdk
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-artifacts
          path: allure-report/